### ISSUE TITLE
Need refactoring

### ISSUE THREAD

**Issue by zhanser1k** [LEVLLN/RecordStudio#6]
Нужно с этим что то сделать @smbkzt 
![image](https://cloud.githubusercontent.com/assets/17352465/20029798/cf486fbe-a388-11e6-9bc0-3f9707d50069.png)

**Comment by ghost** [comment]
Нашел решение данной проблемы. Давай весь код фронта рефакторь под этот, я свою часть исправлю. @zhanser1k 

![image](https://cloud.githubusercontent.com/assets/12483815/20030287/aa817160-a394-11e6-9184-c16c3dbdd581.png)

**Comment by ghost** [comment]
А хотя сам исправь плз бэк. Там только 2 класса оказывается, в остальных методах проверка авторизованного пользователя нужна думаю

![image](https://cloud.githubusercontent.com/assets/12483815/20030338/aaabbe88-a395-11e6-93d8-34b6781445c0.png)
